name: Type check

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on pull request or merge
  pull_request:
  merge_group:
    types: [checks_requested]

defaults:
  run:
    shell: bash
permissions: {}

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install ".[jupyter-executor]" mypy
      # As more modules are type check clean, add them here
      - run: |
          mypy --install-types --non-interactive \
            autogen/logger \
            autogen/exception_utils.py
